function Jf = J_front_ee(in1,in2)
%J_front_ee
%    Jf = J_front_ee(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Nov-2024 00:07:53

p_16 = in2(17,:);
p_18 = in2(19,:);
p_19 = in2(20,:);
p_20 = in2(21,:);
q_2 = in1(3,:);
q_3 = in1(4,:);
q_4 = in1(5,:);
t2 = q_2+q_3;
t3 = cos(t2);
t4 = q_4+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = p_18.*t3;
t9 = p_20.*t3;
t10 = p_18.*t5;
t11 = p_20.*t5;
t12 = p_19.*t6;
t13 = p_19.*t7;
Jf = reshape([1.0,0.0,0.0,1.0,t8+t9+t12-p_16.*sin(q_2),t10+t11+t13+p_16.*cos(q_2),t8+t9+t12,t10+t11+t13,t12,t13,0.0,0.0,0.0,0.0],[2,7]);
end
