function keypoints = keypoints_fn(in1,in2)
%KEYPOINTS_FN
%    KEYPOINTS = KEYPOINTS_FN(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    25-Nov-2024 00:07:54

p_16 = in2(17,:);
p_17 = in2(18,:);
p_18 = in2(19,:);
p_19 = in2(20,:);
p_20 = in2(21,:);
q_0 = in1(1,:);
q_1 = in1(2,:);
q_2 = in1(3,:);
q_3 = in1(4,:);
q_4 = in1(5,:);
q_5 = in1(6,:);
q_6 = in1(7,:);
t2 = cos(q_2);
t3 = sin(q_2);
t4 = q_2+q_3;
t5 = q_2+q_5;
t6 = p_16.*t2;
t7 = cos(t4);
t8 = cos(t5);
t9 = q_4+t4;
t10 = q_6+t5;
t11 = p_16.*t3;
t12 = sin(t4);
t13 = sin(t5);
t14 = cos(t9);
t15 = cos(t10);
t16 = sin(t9);
t17 = sin(t10);
t18 = p_17.*t7;
t19 = p_18.*t7;
t20 = p_17.*t8;
t21 = p_18.*t8;
t22 = p_17.*t12;
t23 = p_18.*t12;
t24 = p_17.*t13;
t25 = p_18.*t13;
t26 = -t6;
t27 = -t11;
t28 = p_19.*t14;
t29 = p_19.*t15;
t30 = p_19.*t16;
t31 = p_19.*t17;
t32 = -t18;
t33 = -t19;
t34 = -t20;
t35 = -t21;
t36 = -t28;
t37 = -t29;
keypoints = reshape([q_0,q_1,q_0+t6,q_1+t11,q_0+t26,q_1+t27,q_0+t6+t22,q_1+t11+t32,q_0+t6+t23,q_1+t11+t33,q_0+t6+t22+t30,q_1+t11+t32+t36,q_0+t6+t23+t30,q_1+t11+t33+t36,q_0+t6+t23+t30+p_20.*t12,q_1+t11+t33+t36-p_20.*t7,q_0+t24+t26,q_1+t27+t34,q_0+t25+t26,q_1+t27+t35,q_0+t24+t26+t31,q_1+t27+t34+t37,q_0+t25+t26+t31,q_1+t27+t35+t37,q_0+t25+t26+t31+p_20.*t13,q_1+t27+t35+t37-p_20.*t8],[2,13]);
end
