function dJf = dJ_front_ee(in1,in2)
%dJ_front_ee
%    dJf = dJ_front_ee(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-Dec-2024 19:20:08

p_16 = in2(17,:);
p_18 = in2(19,:);
p_19 = in2(20,:);
p_20 = in2(21,:);
q_2 = in1(3,:);
q_3 = in1(4,:);
q_4 = in1(5,:);
q_7 = in1(8,:);
q_dot_2 = in1(11,:);
q_dot_3 = in1(12,:);
q_dot_4 = in1(13,:);
q_dot_7 = in1(16,:);
t2 = q_2+q_7;
t3 = cos(t2);
t4 = q_3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = q_4+t4;
t8 = sin(t4);
t9 = p_16.*t3;
t10 = p_16.*t5;
t11 = cos(t7);
t12 = sin(t7);
t13 = p_18.*t6;
t14 = p_20.*t6;
t15 = p_18.*t8;
t16 = p_20.*t8;
t19 = -t10;
t17 = p_19.*t11;
t18 = p_19.*t12;
t20 = q_dot_4.*t17;
t21 = q_dot_4.*t18;
t23 = t13+t14+t17;
t24 = t15+t16+t18;
t22 = -t21;
t25 = q_dot_3.*t23;
t26 = q_dot_3.*t24;
t28 = t9+t24;
t29 = t19+t23;
t27 = -t26;
t30 = q_dot_2.*t28;
t31 = q_dot_7.*t28;
t32 = q_dot_2.*t29;
t33 = q_dot_7.*t29;
t34 = -t30;
t35 = -t31;
t36 = t20+t25+t32+t33;
t37 = t22+t27+t34+t35;
dJf = reshape([0.0,0.0,0.0,0.0,t37,t36,t22+t27-q_dot_2.*t24-q_dot_7.*t24,t20+t25+q_dot_2.*t23+q_dot_7.*t23,t22-q_dot_2.*t18-q_dot_3.*t18-q_dot_7.*t18,t20+q_dot_2.*t17+q_dot_3.*t17+q_dot_7.*t17,0.0,0.0,0.0,0.0,t37,t36],[2,8]);
end
