function Jf = J_front_ee(in1,in2)
%J_front_ee
%    Jf = J_front_ee(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-Dec-2024 19:20:07

p_16 = in2(17,:);
p_18 = in2(19,:);
p_19 = in2(20,:);
p_20 = in2(21,:);
q_2 = in1(3,:);
q_3 = in1(4,:);
q_4 = in1(5,:);
q_7 = in1(8,:);
t2 = q_2+q_7;
t3 = cos(t2);
t4 = q_3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = q_4+t4;
t8 = sin(t4);
t9 = p_16.*t3;
t10 = p_16.*t5;
t11 = cos(t7);
t12 = sin(t7);
t13 = p_18.*t6;
t14 = p_20.*t6;
t15 = p_18.*t8;
t16 = p_20.*t8;
t19 = -t10;
t17 = p_19.*t11;
t18 = p_19.*t12;
t20 = t9+t15+t16+t18;
t21 = t13+t14+t17+t19;
Jf = reshape([1.0,0.0,0.0,1.0,t21,t20,t13+t14+t17,t15+t16+t18,t17,t18,0.0,0.0,0.0,0.0,t21,t20],[2,8]);
end
