function Jh = J_hind_ee(in1,in2)
%J_hind_ee
%    Jh = J_hind_ee(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-Dec-2024 19:20:08

p_16 = in2(17,:);
p_18 = in2(19,:);
p_19 = in2(20,:);
p_20 = in2(21,:);
q_2 = in1(3,:);
q_5 = in1(6,:);
q_6 = in1(7,:);
t2 = q_2+q_5;
t3 = cos(t2);
t4 = q_6+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = sin(t4);
t8 = p_18.*t3;
t9 = p_20.*t3;
t10 = p_18.*t5;
t11 = p_20.*t5;
t12 = p_19.*t6;
t13 = p_19.*t7;
Jh = reshape([1.0,0.0,0.0,1.0,t8+t9+t12+p_16.*sin(q_2),t10+t11+t13-p_16.*cos(q_2),0.0,0.0,0.0,0.0,t8+t9+t12,t10+t11+t13,t12,t13,0.0,0.0],[2,8]);
end
