function out1 = pos_front_ee(in1,in2)
%POS_FRONT_EE
%    OUT1 = POS_FRONT_EE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    01-Dec-2024 19:20:07

p_16 = in2(17,:);
p_18 = in2(19,:);
p_19 = in2(20,:);
p_20 = in2(21,:);
q_0 = in1(1,:);
q_1 = in1(2,:);
q_2 = in1(3,:);
q_3 = in1(4,:);
q_4 = in1(5,:);
q_7 = in1(8,:);
t2 = q_2+q_7;
t3 = q_3+t2;
t4 = cos(t3);
t5 = q_4+t3;
t6 = sin(t3);
out1 = [q_0+p_18.*t6+p_20.*t6+p_16.*cos(t2)+p_19.*sin(t5);q_1-p_18.*t4-p_20.*t4-p_19.*cos(t5)+p_16.*sin(t2)];
end
